Algoritmo "semnome"
// Disciplina   : UC8 ALGORITIMOS
// Professor   : RODRIGO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/05/2025
Var
// Seção de Declarações das variáveis
nome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Qual é o seu nome? ")
leia(nome)
escreva("Olá ",nome," Seja bem vindo!")

Fimalgoritmo