Algoritmo "38-contagem 6 a 11"
// Disciplina   : UC9 ALGORITIMOS
// Professor   : RODRIGO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/05/2025
Var
// Seção de Declarações das variáveis 
x:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
x <-6

enquanto x<=11 FACA
     escreva(x," ")
     x <- x+1
fimenquanto
escreva("Acabou!")

Fimalgoritmo