Algoritmo "39-contagem 10 a 3"
// Disciplina   : UC9 ALGORITIMOS
// Professor   : RODRIGO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/05/2025
Var
// Seção de Declarações das variáveis 
x:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
x <-10

enquanto x>=3 FACA
     escreva(x," ")
     x <- x-1
fimenquanto
escreva("Acabou!")

Fimalgoritmo