Algoritmo "40-contagem 3 em 3 de 0 a 18"
// Disciplina   : UC9 ALGORITIMOS
// Professor   : RODRIGO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/05/2025
Var
// Seção de Declarações das variáveis 
x:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
x <-0

enquanto x<=18 FACA
     escreva(x," ")
     x <- x+3
fimenquanto
escreva("Acabou!")

Fimalgoritmo