Algoritmo "41-contagem 5 em 5 de 100 a 0"
// Disciplina   : UC9 ALGORITIMOS
// Professor   : RODRIGO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/05/2025
Var
// Seção de Declarações das variáveis 
x:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
x <-100

enquanto x>=0 FACA
     escreva(x," ")
     x <- x-5
fimenquanto
escreva("Acabou!")

Fimalgoritmo