Algoritmo "46-Soma 2 em 2 de 6 a 100"
// Disciplina   : UC9 ALGORITIMOS
// Professor   : RODRIGO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/05/2025
Var
// Seção de Declarações das variáveis 
x, i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
i<-6

enquanto i<=100 faca
     escreva(i, " + ")
     x <- x+i
     i <- i+2
fimenquanto

escreva("Total = ",x)
     

Fimalgoritmo