Algoritmo "47-Soma 50 em 50 de 500 a 0"
// Disciplina   : UC9 ALGORITIMOS
// Professor   : RODRIGO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/05/2025
Var
// Seção de Declarações das variáveis 
x, i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
i<-500
x<-0

enquanto i>=0 faca
     escreva(i, " + ")
     x <- x+i
     i <- i-50
fimenquanto

escreva("Total = ",x)
     

Fimalgoritmo