Algoritmo "61-do while sequencia de 3 em 3 até 30"
// Disciplina   : UC9 ALGORITIMOS
// Professor   : RODRIGO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/05/2025
Var
// Seção de Declarações das variáveis 
x:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
repita
escreva(x)
x <- x + 3
até x = 33

escreva("Acabou!")
Fimalgoritmo