Algoritmo "64-for contagem 5 em 5 ate 40"
// Disciplina   : UC9 ALGORITIMOS
// Professor   : RODRIGO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/06/2025
Var
// Seção de Declarações das variáveis 
cont, i:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

para i de 0 ate 8 faca
     escreva(cont," ")
     cont <- cont + 5
     
fimpara

escreva("Acabou!")

Fimalgoritmo