Algoritmo "65-For contagem de 100 ate 0 de 10 em 10"
// Disciplina   : UC9 ALGORITIMOS
// Professor   : RODRIGO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/06/2025
Var
// Seção de Declarações das variáveis 
cont, i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont <- 100

para i de 0 ate 10 faca
     escreva(cont," ")
     cont <- cont-10

fimpara

escreva("Acabou")

Fimalgoritmo