Algoritmo "67-Contagem de 0 ate numero"
// Disciplina   : UC9 ALGORITIMOS
// Professor   : RODRIGO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/06/2025
Var
// Seção de Declarações das variáveis 
num, i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um numero: ")
leia(num)

para i de 0 ate num faca
     escreva(i," ")
fimpara

escreva("Fim!")

Fimalgoritmo