Algoritmo "72-vetores2"
// Disciplina   : UC9 ALGORITIMOS
// Professor   : RODRIGO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/06/2025
Var
// Seção de Declarações das variáveis 
 vet:vetor[0..9] de inteiro
i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
vet[0]<-5

para i de 1 ate 9 faca
     vet[i]<- vet[i-1] + 5
fimpara

Fimalgoritmo