Algoritmo "97-Funcao maior"
// Disciplina   : UC9 ALGORITIMOS
// Professor   : RODRIGO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/06/2025
Var
// Seção de Declarações das variáveis 

   funcao maior(a, b, c:inteiro):inteiro
   
   fimfuncao

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo